language: generic
sudo: required
services: docker

before_install: 
  - docker build -t water34545/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true water34545/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-285163073714"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY