language: generic
sudo: required
services: docker

before_install: 
  - docker build -t water34545/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true water34545/docker-react npm run test